In [20]:
import numpy as np

In [21]:
#Vector
v1 = np.array([10,6,7])
v2 = np.array([20,3,3])
print(v1)
print(v2)
print(type(v1))
print(type(v2))

[10  6  7]
[20  3  3]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [22]:
v3 = v1 + v2
v4 = v1 - v2
v5 = v1 * v2
v6 = v1 / v2
print(v3)
print(v4)
print(v5)
print(v6)

[30  9 10]
[-10   3   4]
[200  18  21]
[0.5        2.         2.33333333]


In [23]:
print(v1.dot(v2))

239


In [24]:
# Matrix
m1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
# Functions for identifying shapes
print(m1.ndim) # no. of dimensions
print(m1.shape) # N * M => Rows * Columns

2
(3, 3)


In [26]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))

mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
vec = np.array([1,2,3,4])
vec.shape[0]

4

In [28]:
mat = vec.reshape((vec.shape[0] , 1))
mat

array([[1],
       [2],
       [3],
       [4]])

In [29]:
# Another Idea for reshaping
vec = np.array([1,2,3,4])

mat = vec[: , None]
mat

array([[1],
       [2],
       [3],
       [4]])

In [30]:
mat = np.array([[1.1,2,3],
                [4,5,6],
                [7,8,9]])

mat.dtype

dtype('float64')

In [31]:
# data type priorety
# Obj - String - Float - Int - Bool

In [32]:
mat = np.array([[1,2,3],
                [4,'5',6],
                [7,8,9]])

float_matrix = mat.astype(int)
print(float_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
vec = np.array([3,2,1,8,9,5,0,4])

vec[2:5]

array([1, 8, 9])

In [34]:
vec[-2:-1]

array([0])

In [35]:
mat = np.array([[1,2,3],['4',5,6],[7,8,9]])
print(mat.dtype)
mat

<U21


array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U21')

In [36]:
class C:
    x= 5

o1 = C()

In [40]:
mat = np.array([[1,2,3],['4',5,6],[7,8,9]])
print(mat.dtype)
mat

<U21


array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U21')

In [42]:
fmat = mat.astype(float)

fmat.dtype


dtype('float64')

In [43]:
v = np.array([3,2,5,1])
v[1]

np.int64(2)

Indexing

In [45]:
mat1 = fmat

mat1[1,2]

np.float64(6.0)

In [47]:
mat1[1,-2]

np.float64(5.0)

In [50]:
mat2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [0,10,20]])

mat2 = mat2.astype(int)
mat2[1:3 , 0:2]

array([[4, 5],
       [7, 8]])

In [52]:
mat2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [0,10,20]])

mat2 = mat2.astype(int)
mat2[-3:-1 , -3:-1]

array([[4, 5],
       [7, 8]])

In [54]:
mat1.T

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

Built in Functions

In [58]:
mat = np.zeros([30000,4])
mat


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], shape=(30000, 4))

In [59]:
mat = np.full((3,3),5)
mat

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [64]:
mat1 = np.empty((3,3))
mat1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [66]:
angle = np.arange(0,361,90)
angle

array([  0,  90, 180, 270, 360])

In [68]:
I = np.identity(3, dtype='float32')
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [70]:
np.random.random((3,3))

array([[0.01622706, 0.60218551, 0.28663869],
       [0.53400127, 0.95029426, 0.60769935],
       [0.54937489, 0.42010756, 0.8537567 ]])

In [72]:
np.random.randint(0,11,(5,5))

array([[ 2,  7, 10,  4,  0],
       [ 3,  8,  6,  5,  3],
       [ 4,  3,  9,  2,  5],
       [ 5,  2, 10,  0,  1],
       [ 3,  5,  5,  4,  6]], dtype=int32)

In [79]:
arr1 = np.zeros((3,3))
arr2 = np.ones((3,3))

np.savez('np_file' , Ones = arr2 , Zeros = arr1)

In [85]:
with np.load('np_file.npz') as file:
    mat_1 = file["Ones"]
    mat_2 = file["Zeros"]

print(f"{mat_1}\n --- \n {mat_2}")

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
 --- 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [86]:
def array_reshape(arr, rows = -1 , cols = -1):
    try:
        arr = np.array(arr)
        return arr.reshape(rows , cols)
    except (TypeError , ValueError) as e:
        raise ValueError(f"Invalid Reshaped operation, check for the size of the array and try again")

In [90]:
array_reshape([1,122,3,43,4,35,25,24,5325,25424] , 2,5)

array([[    1,   122,     3,    43,     4],
       [   35,    25,    24,  5325, 25424]])

In [92]:
v = np.array([1,2,3,4,5,6])

np.all(v >= 1)

np.True_

In [105]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,1,5,3])
print(f"Using all close method: {np.allclose(v1,v2, atol=2)}")
print(f"Using is close method: {np.isclose(v1,v2, atol=2)}")


Using all close method: True
Using is close method: [ True  True  True  True  True]


In [107]:
v = np.array([2,4,3,4,10])

condition = v >= 4

new_arr = np.where(condition , -1 , v)
new_arr

array([ 2, -1,  3, -1, -1])