In [4]:
import numpy as np

In [5]:
#Vector
v1 = np.array([10,6,7])
v2 = np.array([20,3,3])
print(v1)
print(v2)
print(type(v1))
print(type(v2))

[10  6  7]
[20  3  3]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
v3 = v1 + v2
v4 = v1 - v2
v5 = v1 * v2
v6 = v1 / v2
print(v3)
print(v4)
print(v5)
print(v6)

[30  9 10]
[-10   3   4]
[200  18  21]
[0.5        2.         2.33333333]


In [7]:
print(v1.dot(v2))

239


In [8]:
# Matrix
m1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Functions for identifying shapes
print(m1.ndim) # no. of dimensions
print(m1.shape) # N * M => Rows * Columns

2
(3, 3)


In [13]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))

mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
vec = np.array([1,2,3,4])
vec.shape[0]

4

In [20]:
mat = vec.reshape((vec.shape[0] , 1))
mat

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
# Another Idea for reshaping
vec = np.array([1,2,3,4])

mat = vec[: , None]
mat

array([[1],
       [2],
       [3],
       [4]])

In [22]:
mat = np.array([[1.1,2,3],
                [4,5,6],
                [7,8,9]])

mat.dtype

dtype('float64')

In [ ]:
# data type priorety
# Obj - String - Float - Int - Bool

In [25]:
mat = np.array([[1,2,3],
                [4,'5',6],
                [7,8,9]])

float_matrix = mat.astype(int)
print(float_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
vec = np.array([3,2,1,8,9,5,0,4])

vec[2:5]

array([1, 8, 9])

In [28]:
vec[-2:-1]

array([0])